In [6]:
# importing all requried Libraries
import numpy as np
import pandas as pd
import nltk

### 1.Load the data file DailyComments.csv from the Week 4 Data Files into a data frame.

In [7]:
df=pd.read_csv('DailyComments.csv')
df

  Day of Week                                        comments
0      Monday                             Hello, how are you?
1     Tuesday                            Today is a good day!
2   Wednesday  It's my birthday so it's a really special day!
3    Thursday       Today is neither a good day or a bad day!
4      Friday                           I'm having a bad day.
5    Saturday       There' s nothing special happening today.
6      Sunday                      Today is a SUPER good day!

### 2.Identify a scheme to categorize each comment as positive or negative. You can devise your own scheme or find a commonly used scheme to perform this sentiment analysis. However you decide to do this, make sure to explain the scheme you decide to use.

In [8]:
from textblob import TextBlob

I have selected textblob which is a simplified text processing library.It read states that is fairly simple to use, also offer analysis that compares with other algorithms and pacakges.

### 3.Implement your sentiment analysis with code and display the results. Note: DailyComments.csv is a purposely small file, so you will be able to clearly see why the results are what they are.

In [9]:
# defining a function to return the polarity
def sentiment_text(arr):
    return TextBlob(arr).sentiment.polarity

In [10]:
df['polarity']=df['comments'].apply(sentiment_text).round(2)
df

  Day of Week                                        comments  polarity
0      Monday                             Hello, how are you?      0.00
1     Tuesday                            Today is a good day!      0.88
2   Wednesday  It's my birthday so it's a really special day!      0.45
3    Thursday       Today is neither a good day or a bad day!     -0.09
4      Friday                           I'm having a bad day.     -0.70
5    Saturday       There' s nothing special happening today.      0.36
6      Sunday                      Today is a SUPER good day!      0.60

### 4.For up to 5% extra credit, find another set of comments, e.g., some tweets, and perform the same sentiment analysis.

In [11]:
tweets_df=pd.read_csv('tweets.csv')

In [12]:
tweets_df

          id                                              tweet
0      31963  #studiolife #aislife #requires #passion #dedic...
1      31964   @user #white #supremacists want everyone to s...
2      31965  safe ways to heal your #acne!!    #altwaystohe...
3      31966  is the hp and the cursed child book up for res...
4      31967    3rd #bihday to my amazing, hilarious #nephew...
...      ...                                                ...
17192  49155  thought factory: left-right polarisation! #tru...
17193  49156  feeling like a mermaid ð #hairflip #neverre...
17194  49157  #hillary #campaigned today in #ohio((omg)) &am...
17195  49158  happy, at work conference: right mindset leads...
17196  49159  my   song "so glad" free download!  #shoegaze ...

[17197 rows x 2 columns]

In [14]:
tweets_df['polarity']=tweets_df['tweet'].apply(sentiment_text).round(2)
tweets_df

          id                                              tweet  polarity
0      31963  #studiolife #aislife #requires #passion #dedic...      0.00
1      31964   @user #white #supremacists want everyone to s...      0.07
2      31965  safe ways to heal your #acne!!    #altwaystohe...      0.78
3      31966  is the hp and the cursed child book up for res...      0.50
4      31967    3rd #bihday to my amazing, hilarious #nephew...      0.41
...      ...                                                ...       ...
17192  49155  thought factory: left-right polarisation! #tru...      0.00
17193  49156  feeling like a mermaid ð #hairflip #neverre...      0.00
17194  49157  #hillary #campaigned today in #ohio((omg)) &am...      0.00
17195  49158  happy, at work conference: right mindset leads...      0.54
17196  49159  my   song "so glad" free download!  #shoegaze ...      0.50

[17197 rows x 3 columns]